name: "deploy"
on:
  push:
    branches:
      - master
jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        uses: bahmutov/npm-install@master

      - name: Build
        run: npm run build

      - name: Run Jest
        run: npm test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "publish"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
