name: "deploy"
on:
  push:
    branches:
      - master
jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "node"
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: "installation"
        run: npm install
      - name: "test"
        run: npm test
      - name: "publish"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
